name: Push to Docker Hub

on:
  schedule:
  - cron: 32 17 * * *

jobs:
  build: 
    runs-on: ubuntu-18.04 
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@1.12
      with:
        name: singhkays/ffmpeg-av1-libaom
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
